apiVersion: v1
kind: Service
metadata:
  labels:
    app: service_test_pod
  name: echo
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: service_test_pod
  type: ClusterIP
